<input type="checkbox" id="orderNumberCheckbox" checked data-column="Order_Number">Order Number
<input type="checkbox" id="billingAddressCheckbox" checked data-column="Billing_Address">Billing Address
<input type="checkbox" id="shippingAddressCheckbox" checked data-column="Shipping_Address">Shipping Address
<input type="checkbox" id="taxCheckbox" checked data-column="Tax">Tax
<input type="checkbox" id="discountCheckbox" checked data-column="Discount">Discount
<input type="checkbox" id="orderTotalCheckbox" checked data-column="Order_total">Order Total
<input type="checkbox" id="paymentMethodCheckbox" checked data-column="Payment_Method">Payment Method

<div id="myGrid"></div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const gridOptions = {
            rowData: <?php echo $this->getSalesData(); ?>,
            columnDefs: [
                { headerName: "Order Number", field: "Order_Number", minWidth: 170 },
                { headerName: "Billing Address", field: "Billing_Address", minWidth: 500 },
                { headerName: "Shipping Address", field: "Shipping_Address", minWidth: 500 },
                { headerName: "Tax", field: "Tax" },
                { headerName: "Discount", field: "Discount" },
                { headerName: "Order Total", field: "Order_total" },
                { headerName: "Payment Method", field: "Payment_Method" },
            ]
        };
        const myGridElement = document.querySelector('#myGrid');
        const grid = new MyGrid(myGridElement, gridOptions);
        grid.renderGrid(0);
    });
</script>